const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Plugins.Text,
		C3.Plugins.Mouse,
		C3.Plugins.Touch,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Fade,
		C3.Plugins.HTMLElement,
		C3.Plugins.LocalStorage,
		C3.Plugins.AJAX,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.ScriptsInEvents.Gamesheet_Event1_Act2,
		C3.Plugins.LocalStorage.Acts.RemoveItem,
		C3.ScriptsInEvents.Gamesheet_Event2_Act2,
		C3.ScriptsInEvents.Gamesheet_Event3_Act1,
		C3.Plugins.AJAX.Acts.Post,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.ScriptsInEvents.Gamesheet_Event5_Act6,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Plugins.Sprite.Acts.MoveAtAngle,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Behaviors.Tween.Exps.Value,
		C3.Plugins.Text.Acts.SetOpacity,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetY,
		C3.Plugins.Text.Exps.Y,
		C3.ScriptsInEvents.Gamesheet_Event23_Act3
	];
};
self.C3_JsPropNameTable = [
	{Tween: 0},
	{background_loading: 0},
	{loading_bar: 0},
	{Tap_coint_loading: 0},
	{background_game2: 0},
	{Header_shodow_dark2: 0},
	{Header_shodow_light2: 0},
	{Header_text2: 0},
	{Loading_text: 0},
	{Loading_logo: 0},
	{Mouse: 0},
	{background_game: 0},
	{play_bar: 0},
	{Tap_coint: 0},
	{Touch: 0},
	{Fade: 0},
	{RewardFont: 0},
	{Header_text: 0},
	{Header_shodow_light: 0},
	{Header_shodow_dark: 0},
	{score_text: 0},
	{reward_text: 0},
	{Limit_label: 0},
	{Limit_text: 0},
	{limit_bar_ground: 0},
	{limit_bar: 0},
	{Play_button: 0},
	{Play_label: 0},
	{WarningText: 0},
	{ConnectWallet_button: 0},
	{LocalStorage: 0},
	{AJAX: 0},
	{TotalCoin: 0},
	{Limitnumber: 0},
	{WalletConnected: 0},
	{UserID: 0},
	{loadingpro: 0}
];

self.InstanceType = {
	background_loading: class extends self.ISpriteInstance {},
	loading_bar: class extends self.ISpriteInstance {},
	Tap_coint_loading: class extends self.ISpriteInstance {},
	background_game2: class extends self.ISpriteInstance {},
	Header_shodow_dark2: class extends self.ITextInstance {},
	Header_shodow_light2: class extends self.ITextInstance {},
	Header_text2: class extends self.ITextInstance {},
	Loading_text: class extends self.ITextInstance {},
	Loading_logo: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	background_game: class extends self.ISpriteInstance {},
	play_bar: class extends self.ISpriteInstance {},
	Tap_coint: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	RewardFont: class extends self.ISpriteFontInstance {},
	Header_text: class extends self.ITextInstance {},
	Header_shodow_light: class extends self.ITextInstance {},
	Header_shodow_dark: class extends self.ITextInstance {},
	score_text: class extends self.ITextInstance {},
	reward_text: class extends self.ITextInstance {},
	Limit_label: class extends self.ITextInstance {},
	Limit_text: class extends self.ITextInstance {},
	limit_bar_ground: class extends self.ISpriteInstance {},
	limit_bar: class extends self.ISpriteInstance {},
	Play_button: class extends self.ISpriteInstance {},
	Play_label: class extends self.ITextInstance {},
	WarningText: class extends self.ITextInstance {},
	ConnectWallet_button: class extends self.IHTMLElementInstance {},
	LocalStorage: class extends self.IInstance {},
	AJAX: class extends self.IInstance {}
}